// Rich sample demo data celebrating the 8 North-Eastern states of India
export const seedData = {
  caretakers: [
    {
      id: 'caretaker_demo_1',
      fullName: 'Dr. Ananya Sharma',
      email: 'care@memoryroots.in',
      phone: '+91 98765 43210',
      passwordHash: 'demo123', // In demo prototype, matches password
      preferredLanguage: 'en',
      createdAt: '2026-08-15T09:00:00.000Z'
    }
  ],
  patients: [
    {
      id: 'patient_demo_1',
      caretakerId: 'caretaker_demo_1',
      name: 'Biren Sharma (Aita / Koka)',
      age: 74,
      gender: 'Male',
      preferredLanguage: 'en',
      state: 'Assam',
      relationship: 'Father',
      favoriteActivities: ['Listening to Bihu folk songs', 'Walking in the tea garden', 'Reading newspapers on the verandah', 'Gardening local orchids'],
      favoriteFoods: ['Assamese Pitha & Laru', 'Masor Tenga (Sour Fish Curry)', 'Khar with Raw Papaya', 'Hot Dudh Cha (Milk Tea) with Rice Cakes'],
      favoriteSongs: ['Mur Ei Bator Kahini', 'Bhupen Hazarika Classics', 'Bihu Naam on Pepa', 'Old Goalpariya Lokageet'],
      favoritePlaces: ['Majuli Island Brahmaputra ghats', 'Kaziranga grasslands', 'Shillong Ward\'s Lake', 'Childhood ancestral home in Tezpur'],
      childhoodHobbies: ['Playing Guti / 5 Stones under the Banyan tree', 'Flying kites on Autumn afternoons', 'Spinning wooden tops (Latum)', 'Fishing by the village pond'],
      traditionalGames: ['Five Stones (Guti)', 'Marbles (Goli)', 'Spinning Top (Latum)', 'Kite Flying', 'Seed Board Game'],
      importantFamilyMembers: ['Daughter Ananya', 'Son Debojit', 'Granddaughter Rhea (Little Pari)', 'Wife Late Minati'],
      dailyRoutine: 'Wakes at 6:30 AM, morning tea & balcony bird watching, light memory games at 10:00 AM, lunch at 1:00 PM, afternoon rest, family call at 5:30 PM.',
      preferredTimeForActivities: 'Morning (10:00 AM - 11:30 AM)',
      setupCompleted: true,
      questionnaireCompleted: true,
      createdAt: '2026-08-15T09:30:00.000Z'
    }
  ],
  questionnaires: [
    {
      id: 'quest_demo_1',
      patientId: 'patient_demo_1',
      caretakerId: 'caretaker_demo_1',
      answers: {
        recentMemory: 'Sometimes',
        dailyActivities: 'Sometimes',
        familiarPeople: 'Never',
        familiarPlaces: 'Never',
        mood: 'Happy',
        sleep: 'Good',
        socialInteraction: 'Yes'
      },
      profile: {
        visualMemory: 85,
        shortTermRecall: 72,
        recognition: 90,
        attention: 80,
        sequenceMemory: 75,
        dailyRoutineRecall: 88,
        emotionalWellbeing: 92
      },
      completedAt: '2026-08-15T10:00:00.000Z'
    }
  ],
  gameResults: [
    {
        "id": "gr_patient_demo_1_1",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 2000,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-08-31T08:00:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_2",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 92,
        "accuracy": 92,
        "responseTimeMs": 2350,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-08-31T09:17:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_3",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 99,
        "accuracy": 99,
        "responseTimeMs": 2700,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-08-31T10:34:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_4",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 90,
        "accuracy": 90,
        "responseTimeMs": 3050,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-08-31T11:51:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_5",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 97,
        "accuracy": 97,
        "responseTimeMs": 3400,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-08-31T13:08:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_6",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 88,
        "accuracy": 88,
        "responseTimeMs": 3750,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-08-31T14:25:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_7",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 95,
        "accuracy": 95,
        "responseTimeMs": 4100,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-08-31T15:42:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_8",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 86,
        "accuracy": 86,
        "responseTimeMs": 4450,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-08-31T16:59:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_9",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 2000,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-01T08:00:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_10",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 92,
        "accuracy": 92,
        "responseTimeMs": 2350,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-01T09:17:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_11",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 99,
        "accuracy": 99,
        "responseTimeMs": 2700,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-01T10:34:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_12",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 90,
        "accuracy": 90,
        "responseTimeMs": 3050,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-01T11:51:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_13",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 97,
        "accuracy": 97,
        "responseTimeMs": 3400,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-01T12:08:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_14",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 88,
        "accuracy": 88,
        "responseTimeMs": 3750,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-01T13:25:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_15",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 95,
        "accuracy": 95,
        "responseTimeMs": 4100,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-01T14:42:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_16",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 86,
        "accuracy": 86,
        "responseTimeMs": 4450,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-01T15:59:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_17",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 93,
        "accuracy": 93,
        "responseTimeMs": 4800,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-01T16:16:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_18",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 100,
        "accuracy": 100,
        "responseTimeMs": 2150,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-01T17:33:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_19",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 2000,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-02T08:00:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_20",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 92,
        "accuracy": 92,
        "responseTimeMs": 2350,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-02T08:17:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_21",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 99,
        "accuracy": 99,
        "responseTimeMs": 2700,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-02T09:34:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_22",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 90,
        "accuracy": 90,
        "responseTimeMs": 3050,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-02T10:51:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_23",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 97,
        "accuracy": 97,
        "responseTimeMs": 3400,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-02T11:08:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_24",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 88,
        "accuracy": 88,
        "responseTimeMs": 3750,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-02T12:25:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_25",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 95,
        "accuracy": 95,
        "responseTimeMs": 4100,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-02T13:42:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_26",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 86,
        "accuracy": 86,
        "responseTimeMs": 4450,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-02T13:59:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_27",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 93,
        "accuracy": 93,
        "responseTimeMs": 4800,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-02T14:16:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_28",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 100,
        "accuracy": 100,
        "responseTimeMs": 2150,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-02T15:33:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_29",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 91,
        "accuracy": 91,
        "responseTimeMs": 2500,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-02T16:50:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_30",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 98,
        "accuracy": 98,
        "responseTimeMs": 2850,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-02T17:07:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_31",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 2000,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-03T08:00:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_32",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 92,
        "accuracy": 92,
        "responseTimeMs": 2350,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-03T08:17:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_33",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 99,
        "accuracy": 99,
        "responseTimeMs": 2700,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-03T09:34:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_34",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 90,
        "accuracy": 90,
        "responseTimeMs": 3050,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-03T10:51:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_35",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 97,
        "accuracy": 97,
        "responseTimeMs": 3400,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-03T10:08:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_36",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 88,
        "accuracy": 88,
        "responseTimeMs": 3750,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-03T11:25:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_37",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 95,
        "accuracy": 95,
        "responseTimeMs": 4100,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-03T12:42:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_38",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 86,
        "accuracy": 86,
        "responseTimeMs": 4450,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-03T13:59:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_39",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 93,
        "accuracy": 93,
        "responseTimeMs": 4800,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-03T13:16:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_40",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 100,
        "accuracy": 100,
        "responseTimeMs": 2150,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-03T14:33:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_41",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 91,
        "accuracy": 91,
        "responseTimeMs": 2500,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-03T15:50:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_42",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 98,
        "accuracy": 98,
        "responseTimeMs": 2850,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-03T15:07:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_43",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 89,
        "accuracy": 89,
        "responseTimeMs": 3200,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-03T16:24:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_44",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 96,
        "accuracy": 96,
        "responseTimeMs": 3550,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-03T17:41:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_45",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 2000,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-04T08:00:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_46",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 92,
        "accuracy": 92,
        "responseTimeMs": 2350,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-04T08:17:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_47",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 99,
        "accuracy": 99,
        "responseTimeMs": 2700,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-04T09:34:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_48",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 90,
        "accuracy": 90,
        "responseTimeMs": 3050,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-04T09:51:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_49",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 97,
        "accuracy": 97,
        "responseTimeMs": 3400,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-04T10:08:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_50",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 88,
        "accuracy": 88,
        "responseTimeMs": 3750,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-04T10:25:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_51",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 95,
        "accuracy": 95,
        "responseTimeMs": 4100,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-04T11:42:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_52",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 86,
        "accuracy": 86,
        "responseTimeMs": 4450,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-04T12:59:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_53",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 93,
        "accuracy": 93,
        "responseTimeMs": 4800,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-04T12:16:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_54",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 100,
        "accuracy": 100,
        "responseTimeMs": 2150,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-04T13:33:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_55",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 91,
        "accuracy": 91,
        "responseTimeMs": 2500,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-04T13:50:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_56",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 98,
        "accuracy": 98,
        "responseTimeMs": 2850,
        "difficulty": "HARD",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-04T14:07:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_57",
        "patientId": "patient_demo_1",
        "gameId": "letter-c-word",
        "gameName": "Letter C Word Game",
        "category": "Vocabulary & Language Recall",
        "score": 89,
        "accuracy": 89,
        "responseTimeMs": 3200,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-04T15:24:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_58",
        "patientId": "patient_demo_1",
        "gameId": "crosswords",
        "gameName": "Crosswords",
        "category": "Reasoning & Knowledge Recall",
        "score": 96,
        "accuracy": 96,
        "responseTimeMs": 3550,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-04T15:41:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_59",
        "patientId": "patient_demo_1",
        "gameId": "jigsaw-puzzle",
        "gameName": "Jigsaw Puzzle",
        "category": "Visual-Spatial & Motor Coordination",
        "score": 87,
        "accuracy": 87,
        "responseTimeMs": 3900,
        "difficulty": "HARD",
        "level": 1,
        "itemsCount": 6,
        "status": "Completed",
        "completedAt": "2026-09-04T16:58:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_60",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 94,
        "accuracy": 94,
        "responseTimeMs": 4250,
        "difficulty": "EASY",
        "level": 2,
        "itemsCount": 7,
        "status": "Completed",
        "completedAt": "2026-09-04T16:15:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_61",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 4600,
        "difficulty": "MEDIUM",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-04T17:32:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_62",
        "patientId": "patient_demo_1",
        "gameId": "alaska-word-search",
        "gameName": "Alaska Word Search",
        "category": "Concentration & Word Recognition",
        "score": 85,
        "accuracy": 85,
        "responseTimeMs": 2000,
        "difficulty": "EASY",
        "level": 1,
        "itemsCount": 4,
        "status": "Completed",
        "completedAt": "2026-09-05T08:00:00.000Z"
    },
    {
        "id": "gr_patient_demo_1_63",
        "patientId": "patient_demo_1",
        "gameId": "odd-one-out",
        "gameName": "Find Odd One Out",
        "category": "Visual Perception & Attention",
        "score": 92,
        "accuracy": 92,
        "responseTimeMs": 2350,
        "difficulty": "MEDIUM",
        "level": 2,
        "itemsCount": 5,
        "status": "Completed",
        "completedAt": "2026-09-05T13:17:00.000Z"
    }
],
  reminders: [
    {
      id: 'rem_1',
      patientId: 'patient_demo_1',
      title: 'Morning Dudh Cha & Almonds',
      category: 'Meal',
      time: '07:30',
      frequency: 'Daily',
      status: 'active',
      notes: 'Warm tea with two soft rice biscuits on the balcony.'
    },
    {
      id: 'rem_2',
      patientId: 'patient_demo_1',
      title: 'Morning Memory Roots Session',
      category: 'Memory Game',
      time: '10:00',
      frequency: 'Daily',
      status: 'active',
      notes: '10 minutes of gentle Five Stones and Folk Music memory.'
    },
    {
      id: 'rem_3',
      patientId: 'patient_demo_1',
      title: 'Afternoon Hydration (Fresh Coconut Water)',
      category: 'Water',
      time: '12:00',
      frequency: 'Daily',
      status: 'active',
      notes: 'Encourage gentle sips of water or fresh water.'
    },
    {
      id: 'rem_4',
      patientId: 'patient_demo_1',
      title: 'Doctor Recommended Multivitamin',
      category: 'Medication',
      time: '13:30',
      frequency: 'Daily',
      status: 'active',
      notes: 'As entered by Caretaker Dr. Ananya (Post-lunch tablet).'
    },
    {
      id: 'rem_5',
      patientId: 'patient_demo_1',
      title: 'Evening Family Video Call with Granddaughter Rhea',
      category: 'Family Call',
      time: '17:30',
      frequency: 'Daily',
      status: 'active',
      notes: 'Talk about old stories and school days.'
    }
  ],
  familyMemories: [
    {
      id: 'mem_1',
      patientId: 'patient_demo_1',
      title: 'Bihu Festival Celebration in Courtyard',
      category: 'Festival & Family',
      imageUrl: 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=800&q=80',
      description: 'Family gathered together in Tezpur wearing traditional Muga silk Mekhela Sador during Rongali Bihu festival.',
      personOrPlace: 'Granddaughter Rhea & Daughter Ananya in Courtyard',
      questions: [
        {
          questionText: 'Who is dancing joyfully with the Bihu Dhol in this photograph?',
          options: ['Granddaughter Rhea', 'Neighbor Bimal', 'School Teacher', 'Shopkeeper'],
          correctOption: 'Granddaughter Rhea',
          hint: 'Look at the smiling young girl in golden silk.'
        },
        {
          questionText: 'What traditional festival was celebrated here?',
          options: ['Rongali Bihu', 'Diwali', 'New Year Party', 'Sports Day'],
          correctOption: 'Rongali Bihu',
          hint: 'Notice the bamboo decorations and festive sweets.'
        }
      ],
      createdAt: '2026-08-16T12:00:00.000Z'
    },
    {
      id: 'mem_2',
      patientId: 'patient_demo_1',
      title: 'Ancestral Wooden Verandah & Garden',
      category: 'Childhood Home',
      imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
      description: 'The green wooden verandah of the ancestral village home where morning tea and newspaper reading happened every day.',
      personOrPlace: 'Tezpur Ancestral House',
      questions: [
        {
          questionText: 'What favorite morning routine took place on this verandah?',
          options: ['Drinking morning tea & reading newspaper', 'Repairing bicycle', 'Ironing clothes', 'Watching television'],
          correctOption: 'Drinking morning tea & reading newspaper',
          hint: 'Remember the peaceful mornings with the morning birds.'
        }
      ],
      createdAt: '2026-08-18T14:30:00.000Z'
    },
    {
      id: 'mem_3',
      patientId: 'patient_demo_1',
      title: 'Scenic Afternoon at Majuli Island Brahmaputra',
      category: 'Favorite Places',
      imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
      description: 'Tranquil boat journey across the Brahmaputra river near the famous Satras of Majuli.',
      personOrPlace: 'Majuli Riverbank',
      questions: [
        {
          questionText: 'Which mighty river flows beside this serene island?',
          options: ['Brahmaputra', 'Ganga', 'Yamuna', 'Godavari'],
          correctOption: 'Brahmaputra',
          hint: 'The life-giving river of Assam.'
        }
      ],
      createdAt: '2026-08-20T16:00:00.000Z'
    }
  ]
};
